Serhii ponomarov lesson5
Front-End-Pro-2023/Front-End-Pro-2023 pull request #47
Opened 2023-03-18 12:29 UTC by ponomarovs87

2023-03-19 17:06 UTC, SychenkoMykhailo reviewed
hw review

2023-03-19 18:41 UTC, SychenkoMykhailo requested changes
hw 10 review

2023-03-19 18:41 UTC, SychenkoMykhailo commented on src/homeworks/lesson_5/Ponomarov/HW10/script/script.js
> +let temp = 0;
Змінна temp використовується для перевірки на првда чи неправда, краще юзати її саме таким чином, тобто true - якзо є простим, false якщо ні

2023-03-19 18:41 UTC, SychenkoMykhailo commented on src/homeworks/lesson_5/Ponomarov/HW10/script/script.js
> +        temp++;
після зміни temp не потрібно щоб цикл біг далі, щоб його зупинити додай break;

2023-03-19 18:41 UTC, SychenkoMykhailo commented on src/homeworks/lesson_5/Ponomarov/HW10/script/script.js
> +let not = 0;
not як і temp в попередньому завданні виконує ту саму функцію, тому краще щоб воно було true або false

2023-03-19 18:41 UTC, SychenkoMykhailo commented on src/homeworks/lesson_5/Ponomarov/HW10/script/script.js
> +for (i = 1; Math.pow(3, i) <= num; i++) {
загубився let перед i

2023-03-20 05:40 UTC, ponomarovs87 commented on src/homeworks/lesson_5/Ponomarov/HW09/script/script.js
> +document.write(`9.8 Bсі числа в діапазоні від 100 до 200 кратні 3 : <br /> <br/>`);
Спасибо, ошибку исправил

2023-03-20 05:54 UTC, ponomarovs87 commented on src/homeworks/lesson_5/Ponomarov/HW10/script/script.js
> +for (i = 1; Math.pow(3, i) <= num; i++) {
спасибо исправил

2023-03-20 05:55 UTC, ponomarovs87 commented on src/homeworks/lesson_5/Ponomarov/HW10/script/script.js
> +let not = 0;
спасибо исправил

2023-03-20 05:55 UTC, ponomarovs87 commented on src/homeworks/lesson_5/Ponomarov/HW10/script/script.js
> +        temp++;
спасибо исправил

2023-03-20 05:55 UTC, ponomarovs87 commented on src/homeworks/lesson_5/Ponomarov/HW10/script/script.js
> +let temp = 0;
спасибо исправил

2023-05-22 05:45 UTC, merged